version: "3.2"

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      test:
        aliases:
          - postgres

  postgres-boot:
    image: postgres-boot
    container_name: postgres-boot
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    networks:
      test:
        aliases:
          - postgres-boot

volumes:
  pgdata:

networks:
  test:
